FraktalNFT/dapp-frontend

TODO, components/nft-item-opensea/index.tsx, contexts/Web3Context.tsx, pages/index.tsx, pages/my-nfts.tsx, pages/nft/[id]/fix-price-sale.tsx, pages/nft/[id]/manage.tsx, utils/contractCalls.ts, utils/graphQueries.js
Contracts corrected to prevent overflows with tokenIds.
Subgraphs also adapted.
=> reorganization onto contracts with corrections

components/buyOutCard/index.tsx, components/fraktionsDetail/index.tsx
Changing alignment in purchase form to represent the Figma
=> New NFT Fraktion Purchase Form alignment

components/chainWarning/index.tsx
Updated wrong message error to Figma specifics Nov 14 2021
=> Update wrong network message style

pages/my-nfts.tsx
Updated layout to be in line with 
https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=344%3A3061
Images:
=> Update my-nfts layout

package-lock.json, pages/my-nfts.tsx
=> update button text

components/rescueCard/index.tsx
=> updated text

pages/my-nfts.tsx
=> Remove Import Button

components/footer/index.tsx, components/header/index.tsx
=> added view text on wallet button

pages/index.tsx, pages/my-nfts.tsx
closes #66 
@cryptnotiq Please review
=> fix: bug on listNFT page and scroll to your fraktion section

components/button2/index.tsx, components/buyOutCard/index.tsx, components/fraktionsDetail/index.tsx
Added ETH and FRANKTIONS placeholders in Purchase and Buy Block.
=> Add Unit Information in Purchase Block (fixes #74)

components/nft-item/index.tsx, components/userOwnership/index.tsx
Since the action to fraktionalize requires several checks, I added a link to the details page + execute the function to fraktionalize
=> Add button to fraktionalize NFT (fixes #55)

components/offerDetail/index.tsx
=> fixing removed orders

pages/list-nft.tsx
The colors seemed to be already changing to green
=> Auto-trigger metamask when minting and listing NFTs (fixes #115)

components/nft-item/index.tsx, components/offerDetail/index.tsx, pages/my-nfts.tsx, utils/contractCalls.ts
Changes:
1. Reject Offer will call FraktalMarket.rejectOffer() function ⬇️ 
2. If Fraktion is currently listed, "Unlist Fraktions" button will available ⬇️
=> Ui changes on

components/useENSAddress.ts, pages/artist/[...slug].tsx, pages/artists.tsx, utils/stores/ensStore.ts, utils/stores/queries/getQueryENSForETHAddress.ts
How it works:
When a user introduce a string, it will verify if it is a Ethereum address or it's a ENS. In case it's a ENS, it will make a query on ENS subgraph( GraphQL) and then return the corresponding Ethereum address.
=> Search by ens and ETH address

components/buyOutCard/index.tsx, components/fraktionsDetail/index.tsx, components/nft-item/index.tsx, utils/math.ts
Set decimals to a maximum of 3 #151
=> Update decimals for price and min buy to 3

.gitignore, pages/index.tsx
https://github.com/FraktalNFT/dapp-frontend/issues/70
Currently has: Availability (no idea what that means), Popular (?), Newly Listed.
Desired:
Lowest Price
Highest Price
Newly Listed
Popular (# of investors)
Default state should be popular
=> Marketplace Sort Filter Dropdown 

components/layout/index.tsx, components/load-screens/index.tsx, pages/artists.tsx, pages/import-nft.tsx, pages/index.tsx, pages/list-nft.tsx, pages/mint-nft.tsx, pages/nft/[id]/details.tsx, pages/nft/[id]/fix-price-sale.tsx, pages/nft/[id]/list-item.tsx, pages/nft/[id]/manage.tsx
This pull request close this issue: https://github.com/FraktalNFT/dapp-frontend/issues/172
According to the Nextjs docs call to `router.push` takes 2 other option arguments, `router.push(url, as, options)`
The third argument is an object with a `scroll` propery amongst other properties.
`scroll` determines whether to to enable `scroll` animations on navigation to the `url` provided, and is by default set to `true`
We can disable this behavior, responsible for the scroll glitch by adjusting our `router.push()` from `router.push('/my-nfts')` to `router.push('my-nfts, null, {scroll: false)` 
This resolves the scroll glitch for the navigations  to new pages
Update: Fix typos
Sources: https://nextjs.org/docs/api-reference/next/router#routerpush
=> Fix Scroll Bug

components/nft-auction-item/index.tsx, components/nft-item/index.tsx
=> feat: listing type on explore card

components/load-screens/index.tsx, constants/routes.ts, package.json, pages/import-nft.tsx, pages/list-nft.tsx, pages/mint-nft.tsx, redux/actions/contractActions.ts, redux/reducers/loadingScreenReducer.ts, redux/store.ts, types/workflow.ts, utils/contractCalls.ts
Resolve #205 for Minting new NFT and Import NFT cases.
Also fix the redirect loop after listing NFT
=> Loading card tx count

pages/import-nft.tsx, pages/my-nfts.tsx, utils/contractCalls.ts
Importing non-fraktal 1155
https://github.com/FraktalNFT/dapp-frontend/issues/216
Import Opensea NFT for Listing #218
https://github.com/FraktalNFT/dapp-frontend/issues/218
=> Importing non-fraktal 1155

components/buyOutCard/index.tsx
Update make/remove buy out offer button text
=> chore: update text

styles/globals.css, yarn.lock
adjusted styling to match color and theme of other selectors on page!
=> v1 list style change

pages/import-nft.tsx, pages/my-nfts.tsx, utils/contractCalls.ts
Reverts FraktalNFT/dapp-frontend#219
=> Revert "Importing non-fraktal 1155"

pages/import-nft.tsx, pages/list-nft.tsx
Updated listing type tab button design.
Issue url:
https://github.com/FraktalNFT/dapp-frontend/issues/139
=> Update listing type design

pages/explore.tsx
Update fixed/action tab design on explorer page
Commented out show dropdown as it was for testing only
=> Update fixed/action tab design

components/fraktionsList/index.tsx, components/verifyNFT/index.tsx, pages/nft/[id]/auction.tsx, utils/graphQueries.js, utils/openSeaAPI.ts
https://github.com/FraktalNFT/dapp-frontend/issues/272
https://github.com/FraktalNFT/dapp-frontend/issues/271
=> Add verify NFT button to /auction pages #271

components/userOwnership/index.tsx, contexts/userContext.tsx, pages/nft/[id]/list-item.tsx
https://github.com/FraktalNFT/dapp-frontend/issues/318
=> 318 defrak and claim 2

components/media/index.tsx, pages/nft/[id]/auction.tsx, pages/nft/[id]/details.tsx, utils/nftHelpers.js
MP4:
nft/0xd7a8c54b9659a1fea068c24f915b66cde457593c/details
nft/0xc3a6b9543519f25eB3b7098fB0Bfe401Ada0F160/details
nft/0xab5b44f801c81d34c6e08ab02b3b6c73f7c95304/details
nft/0xd7a8c54b9659a1fea068c24f915b66cde457593c/details
nft/0xb30a6c9583a3b75f3a7d82c5d7ef08d88cc87443/details
GIF:
nft/0xd98275e18469a70dca4efce04812bb929c79784b-0/auction
nft/0x73d5cabf1c0b8a3e5ea174658d431fbf92b8694f/details
=> NFT details: Video/GIF display

components/media/index.tsx, pages/nft/[id]/details.tsx, utils/nftHelpers.js
https://fraktal-dapp-git-fork-alexsnipes-video-circle-fix-fraktal.vercel.app/nft/0x54796603015e5f38eecc4960088b597cd6b86329/details
=>  Inner Circle - Pink Realm  fix
